package view;

public class VoluntarioFormView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VoluntarioFormView.class.getName());

    public VoluntarioFormView() {
        initComponents();
        mainPanel.add(paginaInicio, "paginaInicio");
        mainPanel.add(paginaFormulario1, "paginaFormulario1");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        paginaInicio = new javax.swing.JPanel();
        btn_tomarFormulario = new javax.swing.JButton();
        paginaFormulario1 = new javax.swing.JPanel();
        TEXTO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setExtendedState(java.awt.Frame.MAXIMIZED_BOTH
        );
        setFocusable(false);
        setPreferredSize(new java.awt.Dimension(640, 360));

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));
        mainPanel.setLayout(new java.awt.CardLayout());

        paginaInicio.setBackground(new java.awt.Color(255, 255, 255));
        paginaInicio.setLayout(new java.awt.GridBagLayout());

        btn_tomarFormulario.setBackground(new java.awt.Color(215, 85, 85));
        btn_tomarFormulario.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        btn_tomarFormulario.setForeground(new java.awt.Color(255, 255, 255));
        btn_tomarFormulario.setText("TOMAR FORMULARIO");
        btn_tomarFormulario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_tomarFormularioActionPerformed(evt);
            }
        });
        paginaInicio.add(btn_tomarFormulario, new java.awt.GridBagConstraints());

        mainPanel.add(paginaInicio, "card2");

        paginaFormulario1.setBackground(new java.awt.Color(255, 255, 255));
        paginaFormulario1.setLayout(new java.awt.GridBagLayout());

        TEXTO.setBackground(new java.awt.Color(255, 255, 255));
        TEXTO.setFont(new java.awt.Font("Consolas", 1, 18)); // NOI18N
        TEXTO.setForeground(new java.awt.Color(0, 0, 0));
        TEXTO.setText("Bienvenido al formulario de registro de voluntariado!");
        paginaFormulario1.add(TEXTO, new java.awt.GridBagConstraints());

        mainPanel.add(paginaFormulario1, "card3");

        getContentPane().add(mainPanel, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_tomarFormularioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_tomarFormularioActionPerformed
        java.awt.CardLayout card = (java.awt.CardLayout)(mainPanel.getLayout());
        card.show(mainPanel, "paginaFormulario1");
    }//GEN-LAST:event_btn_tomarFormularioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VoluntarioFormView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TEXTO;
    private javax.swing.JButton btn_tomarFormulario;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JPanel paginaFormulario1;
    private javax.swing.JPanel paginaInicio;
    // End of variables declaration//GEN-END:variables
}
